version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build # only if your app has a build step, otherwise omit this line
artifacts:
  files:
    - '**/*'
